version: 0.1

phases:
  build:
    commands:
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -q
      - apt install -y openjdk-11-jdk
      - export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
      - mvn -version
      - mvn install

artifacts:
  files:
    - webgoat-server/target/webgoat-server-8.0-SNAPSHOT.jar
  discard-paths: yes

